// StrictJsonMiddleware.cs to enforce strict JSON property validation
using System.Text.Json;
using System.Text;
using TeacherAPI.Models;

public class StrictJsonMiddleware
{
    private readonly RequestDelegate _next;

    public StrictJsonMiddleware(RequestDelegate next) => _next = next;

    public async Task InvokeAsync(HttpContext context)
    {
        if ((context.Request.Method == "POST" || context.Request.Method == "PUT") &&
            context.Request.ContentType?.Contains("application/json") == true)
        {
            context.Request.EnableBuffering(); // Allow multiple reads

            using var reader = new StreamReader(context.Request.Body, Encoding.UTF8, leaveOpen: true);
            var body = await reader.ReadToEndAsync();
            context.Request.Body.Position = 0;

            if (!string.IsNullOrWhiteSpace(body))
            {
                try
                {
                    using var doc = JsonDocument.Parse(body);

                    // Allowed properties from Teacher model
                    var allowedProps = typeof(Teacher).GetProperties().Select(p => p.Name).ToHashSet();

                    foreach (var prop in doc.RootElement.EnumerateObject())
                    {
                        if (!allowedProps.Contains(prop.Name))
                        {
                            context.Response.StatusCode = StatusCodes.Status400BadRequest;
                            await context.Response.WriteAsJsonAsync(new
                            {
                                error = $"Property '{prop.Name}' is invalid or does not match expected casing."
                            });
                            return;
                        }

                        // Reject Id on POST
                        if (prop.Name == "Id" && context.Request.Method == "POST")
                        {
                            context.Response.StatusCode = StatusCodes.Status400BadRequest;
                            await context.Response.WriteAsJsonAsync(new
                            {
                                error = "The 'Id' field is not required and will be generated by the server."
                            });
                            return;
                        }
                    }
                }
                catch (JsonException)
                {
                    context.Response.StatusCode = StatusCodes.Status400BadRequest;
                    await context.Response.WriteAsJsonAsync(new { error = "Invalid JSON format." });
                    return;
                }
            }
        }

        await _next(context);
    }
}
