// <auto-generated />
using System;
using APIBusSeatBookingManagement.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIBusSeatBookingManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204061148_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"));

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("BusId");

                    b.HasIndex("BusNumber")
                        .IsUnique();

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            BusId = 1,
                            BusNumber = "KA01AB1234",
                            BusType = "AC",
                            CreatedAt = new DateTime(2025, 12, 4, 6, 11, 47, 891, DateTimeKind.Utc).AddTicks(4602),
                            TotalSeats = 40
                        },
                        new
                        {
                            BusId = 2,
                            BusNumber = "MD02DB5237",
                            BusType = "Non-Ac",
                            CreatedAt = new DateTime(2025, 12, 4, 6, 11, 47, 891, DateTimeKind.Utc).AddTicks(4605),
                            TotalSeats = 50
                        },
                        new
                        {
                            BusId = 3,
                            BusNumber = "NP02DB8547",
                            BusType = "Sleeper",
                            CreatedAt = new DateTime(2025, 12, 4, 6, 11, 47, 891, DateTimeKind.Utc).AddTicks(4607),
                            TotalSeats = 30
                        });
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("paymentTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Routes", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            DistanceKm = 310.0,
                            DurationMinutes = 300,
                            FromLocation = "Kathmandu",
                            ToLocation = "Pokhara"
                        },
                        new
                        {
                            RouteId = 2,
                            DistanceKm = 310.0,
                            DurationMinutes = 300,
                            FromLocation = "Daran",
                            ToLocation = "Pokhara"
                        },
                        new
                        {
                            RouteId = 3,
                            DistanceKm = 310.0,
                            DurationMinutes = 300,
                            FromLocation = "Kathmandu",
                            ToLocation = "chitwan"
                        });
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("BusId");

                    b.HasIndex("RouteId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SeatId");

                    b.HasIndex("ScheduleId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 12, 4, 6, 11, 47, 891, DateTimeKind.Utc).AddTicks(4474),
                            Email = "admin@busbooking.com",
                            FullName = "Admin User",
                            Password = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 12, 4, 6, 11, 47, 891, DateTimeKind.Utc).AddTicks(4494),
                            Email = "Staff@busbooking.com",
                            FullName = "Staff User",
                            Password = "LwBeQqF9pG7FG6bxHXJeYHiJMaHa3TPZy4UIT7MrsWY=",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 12, 4, 6, 11, 47, 891, DateTimeKind.Utc).AddTicks(4508),
                            Email = "Customer@busbooking.com",
                            FullName = "Customer User",
                            Password = "phqK32ADh5Kiy4jmcLIFQKnWwsogSrdU/HaJUOeefTY=",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Booking", b =>
                {
                    b.HasOne("APIBusSeatBookingManagement.Model.Schedule", "Schedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIBusSeatBookingManagement.Model.Seat", "Seat")
                        .WithMany("Booking")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIBusSeatBookingManagement.Model.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Payment", b =>
                {
                    b.HasOne("APIBusSeatBookingManagement.Model.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("APIBusSeatBookingManagement.Model.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Schedule", b =>
                {
                    b.HasOne("APIBusSeatBookingManagement.Model.Bus", "Bus")
                        .WithMany("Schedules")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIBusSeatBookingManagement.Model.Routes", "Route")
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Seat", b =>
                {
                    b.HasOne("APIBusSeatBookingManagement.Model.Schedule", "Schedule")
                        .WithMany("Seats")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Booking", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Bus", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Routes", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Schedule", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.Seat", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("APIBusSeatBookingManagement.Model.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
